# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11rpc_service.proto\x12\x08\x62iStream"2\n\x04\x44\x61ta\x12\x0c\n\x04\x41\x63\x63V\x18\x01 \x01(\x02\x12\r\n\x05\x41\x63\x63ML\x18\x02 \x01(\x02\x12\r\n\x05\x41\x63\x63\x41P\x18\x03 \x01(\x02"D\n\nPrediction\x12\x17\n\x0fStartHesitation\x18\x01 \x01(\x05\x12\x0c\n\x04Turn\x18\x02 \x01(\x05\x12\x0f\n\x07Walking\x18\x03 \x01(\x05\x32J\n\x07Package\x12?\n\x13\x62idirectionalStream\x12\x0e.biStream.Data\x1a\x14.biStream.Prediction(\x01\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "rpc_service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_DATA"]._serialized_start = 31
    _globals["_DATA"]._serialized_end = 81
    _globals["_PREDICTION"]._serialized_start = 83
    _globals["_PREDICTION"]._serialized_end = 151
    _globals["_PACKAGE"]._serialized_start = 153
    _globals["_PACKAGE"]._serialized_end = 227
# @@protoc_insertion_point(module_scope)
