tdcsfog:
  tf_record_path: data/processed/tdcsfog/cnn.tfrecords
  input_size: ((328, 3), (3,))
  training_units:
    filter:
      - 128
      - 64
      - 32
      - 16
      - 8
    units:
      - 289
      - 169
      - 121
      - 49
      - 25
      - 9

defog:
  tf_record_path: data/processed/defog/cnn.tfrecords
  input_size: ((256, 3), (3,))
  training_units:
    filter:
      - 128
      - 64
      - 32
      - 16
      - 8
    units:
      - 289
      - 169
      - 121
      - 49
      - 25
      - 9