tdcsfog:
  tf_record_path: data/processed/tdcsfog_cnn.tfrecords
  input_size: ((328, 3), (3,))
  training_units:
    - 256
    - 169
    - 121
    - 49
    - 25
    - 9

defog:
  tf_record_path: data/processed/defog_cnn.tfrecords
  input_size: ((256, 3), (3,))
  training_units:
    - 256
    - 169
    - 121
    - 49
    - 25
    - 9
