# To get the tensorflow with cuda drivers pre installed.
FROM tensorflow/tensorflow:2.12.0-gpu

# Changing the working directory from root to Parkinsons_FOG
WORKDIR /root/Parkinsons_FOG

# Copying the files from host machine to the docker image.
COPY api_main.py api_entrypoint.sh requirements.txt ./

# Installing the necessary libraries for python form the requirements.txt file.
RUN chmod +x api_entrypoint.sh \
    && apt-get update \
    && apt-get install iproute2 -y \
    && apt-get install iputils-ping -y \
    && apt-get install traceroute \
    && apt-get install nano \
    && pip install -r requirements.txt

# Copying the folders with their contents from host machine to Docker Image.
COPY api api
COPY grpc_stream grpc_stream
COPY logger_config logger_config
COPY src src
COPY tests tests

## PERSISTANT DATA SPACES WITHIN THE IMAGE
# These are expected to be mounts form the host machine.
VOLUME /root/Parkinsons_FOG/config
VOLUME /root/Parkinsons_FOG/data
VOLUME /root/Parkinsons_FOG/logs
VOLUME /root/Parkinsons_FOG/models/ModelSaves

# This is expected to be a docker volume.
VOLUME /root/Parkinsons_FOG/models/ModelCheckpoint

EXPOSE 8080

# The First Command to be executed when a Docker Contaner is created, here it is to run the APIs.
ENTRYPOINT ["sh", "api_entrypoint.sh"]
