stages:
  process_tdcsfog_metadata:
    cmd: jupyter notebook
    deps:
    - data/raw/events.csv
    - data/raw/subjects.csv
    - data/raw/tdcsfog_metadata.csv
    - notebooks/tdcsfog_metadata_processing.ipynb
    outs:
    - data/processed/tdcsfog/processed_tdcsfog_metadata.csv
  process_tdcsfog_train_data:
    cmd: -0 data/processed/tdcsfog/rnn.tfrecords python main.py
    deps:
    - data/processed/tdcsfog/processed_tdcsfog_metadata.csv
    - src/config.py
    outs:
    - data/processed/tdcsfog/cnn.tfrecords
