stages:
  process_tdcsfog_metadata:
    cmd: jupyter notebook
    deps:
    - data/raw/events.csv
    - data/raw/subjects.csv
    - data/raw/tdcsfog_metadata.csv
    - notebooks/tdcsfog_metadata_processing.ipynb
    outs:
    - data/processed/tdcsfog/processed_tdcsfog_metadata.csv
  process_tdcsfog_train_data:
    cmd: python main.py
    deps:
    - data/processed/tdcsfog/processed_tdcsfog_metadata.csv
    - src/config.py
    outs:
    - data/processed/tdcsfog/cnn.tfrecords
    - data/processed/tdcsfog/rnn.tfrecords
  process_defog_metadata:
    cmd: jupyter notebook
    deps:
    - data/raw/defog_metadata.csv
    - data/raw/events.csv
    - data/raw/subjects.csv
    - data/raw/tasks.csv
    - notebooks/defog_metadata_processing.ipynb
    outs:
    - data/processed/defog/processed_defog_metadata.csv
  process_defog_train_data:
    cmd: python main.py
    deps:
    - data/processed/defog/processed_defog_metadata.csv
    - src/config.py
    outs:
    - data/processed/defog/cnn.tfrecords
    - data/processed/defog/rnn.tfrecords
