type: tdcsfog
metadata: data/processed/tdcsfog/processed_tdcsfog_metadata.csv
dataset: data/raw/train/tdcsfog/
tf_record_path:
  rnn: data/processed/tdcsfog/rnn.tfrecords
  cnn: data/processed/tdcsfog/cnn.tfrecords
window_size: 328
steps: 102
power_spectrum:
  type: RNN
  freq: 128
