name: Parallel Python Execution

on:
  push:
    branches:
      - master

jobs:
  execute_python:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify your Python version here

    - name: Install Python Dependencies
      run: pip install -r requirements.txt  # Replace with the path to your requirements file

    - name: Execute Scripts 2 and 3 in Parallel
      run: |
        python api_main.py &
        python streamlit_main.py &

    - name: Wait for scripts 2 and 3 to complete
      run: wait
