name: Check Execution.

on:
  workflow_run:
    workflows: ["continuous_integration"]
    types:
      - completed

jobs:
  execute_python:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Execute Scripts api_main.py and streamlit_main.py in Parallel
      run: |
        python api_main.py &
        python streamlit_main.py &

    - name: Execute Scripts api_main.py and streamlit_main.py in Parallel
      run: wait

    - name: Stop api_main.py
      run: pkill -f "python api_main.py"

    - name: Stop streamlit_main.py
      run: pkill -f "python streamlit_main.py"
